In [1]:
import numpy as np
import pandas as  pd

In [2]:
df=pd.read_csv('Churn_Modelling.csv')
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
df=df.iloc[:,3:]
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [5]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [6]:
df=pd.get_dummies(df,columns=['Gender','Geography'],drop_first=True)

In [7]:
x=df.drop(columns=['Exited'])
y=df['Exited']

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
st=StandardScaler()
x_scaled=st.fit_transform(x)
x_scaled

array([[-0.32622142,  0.29351742, -1.04175968, ..., -1.09598752,
        -0.57873591, -0.57380915],
       [-0.44003595,  0.19816383, -1.38753759, ..., -1.09598752,
        -0.57873591,  1.74273971],
       [-1.53679418,  0.29351742,  1.03290776, ..., -1.09598752,
        -0.57873591, -0.57380915],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -1.09598752,
        -0.57873591, -0.57380915],
       [ 1.25683526,  0.29351742, -0.69598177, ...,  0.91241915,
         1.72790383, -0.57380915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -1.09598752,
        -0.57873591, -0.57380915]])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.20,random_state=1)

In [12]:
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(8000, 11) (8000,)
(2000, 11) (2000,)

In [13]:
# pip install tensorflow

In [14]:
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [64]:
model=Sequential()
model.add(Dense(11,activation='relu',input_dim=11))
model.add(Dense(11,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

C:\Users\cipl\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [66]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 11)                  │             132 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 11)                  │             132 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │              12 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [111]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [115]:
model.fit(x_train,y_train,epochs=100,validation_split=0.2)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8673 - loss: 0.3187 - val_accuracy: 0.8637 - val_loss: 0.3172
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8671 - loss: 0.3138 - val_accuracy: 0.8625 - val_loss: 0.3209
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8634 - loss: 0.3291 - val_accuracy: 0.8612 - val_loss: 0.3206
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8654 - loss: 0.3193 - val_accuracy: 0.8656 - val_loss: 0.3215
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8611 - loss: 0.3273 - val_accuracy: 0.8662 - val_loss: 0.3241
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8656 - loss: 0.3232 - val_accuracy: 0.8650 - val_loss: 0.3230
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8695 - loss: 0.3160 - val_accuracy: 0.8650 - val_loss: 0.3235
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8697 - loss: 0.3175 - val_accuracy: 0.8631 - val_loss: 0.3262
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8726 - loss: 0.3202 - val_accuracy: 0.8600 - val_loss: 0.3276
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8718 - loss: 0.3129 - val_accuracy: 0.8619 - val_loss: 0.3256
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8711 - loss: 0.3149 - val_accuracy: 0.8612 - val_loss: 0.3266
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8652 - loss: 0.3238 - val_accuracy: 0.8594 - val_loss: 0.3282
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8693 - loss: 0.3144 - val_accuracy: 0.8637 - val_loss: 0.3260
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8727 - loss: 0.3117 - val_accuracy: 0.8619 - val_loss: 0.3261
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8657 - loss: 0.3196 - val_accuracy: 0.8631 - val_loss: 0.3264
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8686 - loss: 0.3194 - val_accuracy: 0.8612 - val_loss: 0.3282
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8731 - loss: 0.3114 - val_accuracy: 0.8569 - val_loss: 0.3307
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8641 - loss: 0.3194 - val_accuracy: 0.8569 - val_loss: 0.3291
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8641 - loss: 0.3147 - val_accuracy: 0.8637 - val_loss: 0.3276
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8733 - loss: 0.3045 - val_accuracy: 0.8612 - val_loss: 0.3297
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8670 - loss: 0.3177 - val_accuracy: 0.8631 - val_loss: 0.3303
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8642 - loss: 0.3266 - val_accuracy: 0.8575 - val_loss: 0.3321
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8766 - loss: 0.3009 - val_accuracy: 0.8575 - val_loss: 0.3308
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8712 - loss: 0.3072 - val_accuracy: 0.8581 - val_loss: 0.3345
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8686 - loss: 0.3122 - val_accuracy: 0.8625 - val_loss: 0.3293
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8708 - loss: 0.3053 - val_accuracy: 0.8587 - val_loss: 0.3308
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8743 - loss: 0.3093 - val_accuracy: 0.8556 - val_loss: 0.3326
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8753 - loss: 0.3099 - val_accuracy: 0.8594 - val_loss: 0.3299
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8737 - loss: 0.3058 - val_accuracy: 0.8594 - val_loss: 0.3312
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8641 - loss: 0.3218 - val_accuracy: 0.8594 - val_loss: 0.3339
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8692 - loss: 0.3142 - val_accuracy: 0.8594 - val_loss: 0.3311
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8793 - loss: 0.2913 - val_accuracy: 0.8587 - val_loss: 0.3305
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8703 - loss: 0.3094 - val_accuracy: 0.8550 - val_loss: 0.3357
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8722 - loss: 0.3090 - val_accuracy: 0.8587 - val_loss: 0.3312
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8704 - loss: 0.3181 - val_accuracy: 0.8587 - val_loss: 0.3301
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8629 - loss: 0.3277 - val_accuracy: 0.8619 - val_loss: 0.3310
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8666 - loss: 0.3174 - val_accuracy: 0.8594 - val_loss: 0.3341
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8775 - loss: 0.3080 - val_accuracy: 0.8625 - val_loss: 0.3306
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8707 - loss: 0.3118 - val_accuracy: 0.8587 - val_loss: 0.3332
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8711 - loss: 0.3170 - val_accuracy: 0.8594 - val_loss: 0.3328
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8770 - loss: 0.3059 - val_accuracy: 0.8550 - val_loss: 0.3396
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8621 - loss: 0.3302 - val_accuracy: 0.8606 - val_loss: 0.3319
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8709 - loss: 0.3102 - val_accuracy: 0.8575 - val_loss: 0.3328
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8786 - loss: 0.2984 - val_accuracy: 0.8587 - val_loss: 0.3351
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8669 - loss: 0.3141 - val_accuracy: 0.8562 - val_loss: 0.3339
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8787 - loss: 0.2970 - val_accuracy: 0.8556 - val_loss: 0.3351
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8717 - loss: 0.3096 - val_accuracy: 0.8556 - val_loss: 0.3361
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8737 - loss: 0.3096 - val_accuracy: 0.8600 - val_loss: 0.3354
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8669 - loss: 0.3173 - val_accuracy: 0.8587 - val_loss: 0.3365
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8712 - loss: 0.3060 - val_accuracy: 0.8594 - val_loss: 0.3353
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8700 - loss: 0.3093 - val_accuracy: 0.8587 - val_loss: 0.3351
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8657 - loss: 0.3203 - val_accuracy: 0.8581 - val_loss: 0.3366
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8723 - loss: 0.3133 - val_accuracy: 0.8569 - val_loss: 0.3359
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8754 - loss: 0.3059 - val_accuracy: 0.8569 - val_loss: 0.3367
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8677 - loss: 0.3197 - val_accuracy: 0.8581 - val_loss: 0.3402
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8759 - loss: 0.3064 - val_accuracy: 0.8581 - val_loss: 0.3389
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8634 - loss: 0.3191 - val_accuracy: 0.8562 - val_loss: 0.3394
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8636 - loss: 0.3187 - val_accuracy: 0.8569 - val_loss: 0.3357
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8776 - loss: 0.3044 - val_accuracy: 0.8556 - val_loss: 0.3356
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8670 - loss: 0.3247 - val_accuracy: 0.8569 - val_loss: 0.3408
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8710 - loss: 0.3080 - val_accuracy: 0.8569 - val_loss: 0.3376
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8684 - loss: 0.3094 - val_accuracy: 0.8562 - val_loss: 0.3378
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8717 - loss: 0.3099 - val_accuracy: 0.8562 - val_loss: 0.3390
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8742 - loss: 0.3059 - val_accuracy: 0.8575 - val_loss: 0.3376
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8723 - loss: 0.3103 - val_accuracy: 0.8612 - val_loss: 0.3357
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8660 - loss: 0.3172 - val_accuracy: 0.8569 - val_loss: 0.3392
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8681 - loss: 0.3144 - val_accuracy: 0.8587 - val_loss: 0.3384
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8650 - loss: 0.3162 - val_accuracy: 0.8550 - val_loss: 0.3436
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8730 - loss: 0.3105 - val_accuracy: 0.8550 - val_loss: 0.3382
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8724 - loss: 0.3013 - val_accuracy: 0.8562 - val_loss: 0.3383
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8706 - loss: 0.3126 - val_accuracy: 0.8594 - val_loss: 0.3417
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8688 - loss: 0.3112 - val_accuracy: 0.8587 - val_loss: 0.3390
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8706 - loss: 0.3097 - val_accuracy: 0.8569 - val_loss: 0.3394
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8730 - loss: 0.3061 - val_accuracy: 0.8550 - val_loss: 0.3392
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8752 - loss: 0.2966 - val_accuracy: 0.8562 - val_loss: 0.3406
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8649 - loss: 0.3181 - val_accuracy: 0.8569 - val_loss: 0.3384
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8680 - loss: 0.3121 - val_accuracy: 0.8531 - val_loss: 0.3419
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8730 - loss: 0.3139 - val_accuracy: 0.8525 - val_loss: 0.3403
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8744 - loss: 0.3121 - val_accuracy: 0.8562 - val_loss: 0.3416
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8684 - loss: 0.3114 - val_accuracy: 0.8569 - val_loss: 0.3402
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8693 - loss: 0.3082 - val_accuracy: 0.8581 - val_loss: 0.3382
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8702 - loss: 0.3138 - val_accuracy: 0.8569 - val_loss: 0.3414
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8732 - loss: 0.3069 - val_accuracy: 0.8531 - val_loss: 0.3432
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8722 - loss: 0.3060 - val_accuracy: 0.8562 - val_loss: 0.3422
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8682 - loss: 0.3134 - val_accuracy: 0.8562 - val_loss: 0.3411
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8742 - loss: 0.3098 - val_accuracy: 0.8525 - val_loss: 0.3404
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8718 - loss: 0.3050 - val_accuracy: 0.8594 - val_loss: 0.3385
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8708 - loss: 0.3069 - val_accuracy: 0.8531 - val_loss: 0.3442
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8734 - loss: 0.3108 - val_accuracy: 0.8537 - val_loss: 0.3423
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8726 - loss: 0.3081 - val_accuracy: 0.8537 - val_loss: 0.3424
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8727 - loss: 0.3163 - val_accuracy: 0.8544 - val_loss: 0.3415
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8758 - loss: 0.3065 - val_accuracy: 0.8550 - val_loss: 0.3398
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8786 - loss: 0.2997 - val_accuracy: 0.8575 - val_loss: 0.3428
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8802 - loss: 0.2938 - val_accuracy: 0.8562 - val_loss: 0.3421
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8615 - loss: 0.3156 - val_accuracy: 0.8562 - val_loss: 0.3441
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8728 - loss: 0.2994 - val_accuracy: 0.8531 - val_loss: 0.3414
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8670 - loss: 0.3119 - val_accuracy: 0.8581 - val_loss: 0.3424
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8815 - loss: 0.2907 - val_accuracy: 0.8525 - val_loss: 0.3410
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8707 - loss: 0.3046 - val_accuracy: 0.8575 - val_loss: 0.3404
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8696 - loss: 0.3179 - val_accuracy: 0.8581 - val_loss: 0.3400

In [117]:
model.layers[0].get_weights()

[array([[ 3.7025280e-02, -1.6333276e-01, -1.6826591e-01, -7.4351251e-01,
          2.7645642e-01,  1.5543716e-01,  1.2055179e-02, -6.5641850e-01,
         -9.1095082e-02,  1.5259841e-01,  3.4790862e-01],
        [-8.0952233e-01, -1.4341806e-01,  5.0350361e-02,  3.2314232e-01,
         -5.9810257e-01,  2.9359883e-01,  6.7998540e-01,  7.5752079e-02,
         -2.6362345e-01,  5.4898745e-01,  1.3111413e-02],
        [ 5.5344374e-04,  1.2752075e-01,  8.2477458e-02,  6.2868595e-01,
         -2.6703796e-01, -9.3192473e-02,  1.0830990e-01, -2.7012303e-01,
         -3.1691605e-01,  3.6875996e-01, -1.8416055e-01],
        [-5.4099159e-03, -9.4469333e-01, -7.8838795e-02, -9.3519293e-02,
         -3.5407093e-01,  3.8209149e-01,  7.4935961e-03,  6.6858083e-01,
          4.2483512e-02, -7.8756720e-01,  3.4152374e-01],
        [-4.1121542e-02, -3.6043537e-01, -1.3704913e+00, -1.7787513e-01,
         -2.5347066e-01,  1.1008704e+00,  4.4614058e-02, -2.2277167e-02,
         -3.0212262e-01, -6.9359589e-01, -2.9065678e-01],
        [-5.4049410e-02,  1.8641484e-01,  1.0967004e-01,  4.8868772e-01,
          6.0836351e-01,  1.5797731e-02,  1.4350680e-01,  1.4440456e-01,
         -3.0003136e-01, -8.4122753e-01,  3.0971959e-01],
        [-2.1609966e-01,  1.3760167e-01, -1.6959806e-01, -1.6681556e-01,
          1.6651724e-01,  2.3179971e-01,  8.1945413e-01,  2.6553676e-01,
          5.6505913e-01,  3.0515221e-01,  1.6790555e-01],
        [ 1.0094726e-01, -1.4659712e-01,  2.4677059e-01, -1.3876766e-01,
          8.6307880e-03,  2.6652285e-01,  1.2808044e-01, -2.8914967e-01,
         -2.6807746e-01, -3.8769182e-02,  5.0990272e-01],
        [ 1.1927798e-01,  5.6548119e-01, -1.8838037e-02,  9.0075098e-02,
          7.6749581e-01, -7.3089846e-03,  1.5283562e-01,  6.5469348e-01,
          2.0433807e-01, -2.7369440e-01, -7.3787850e-01],
        [-7.5317426e-03, -5.6822193e-01,  2.4653421e-01,  8.3319649e-02,
         -7.6101732e-01, -1.2151871e-02, -7.2611704e-02,  6.3429184e-02,
         -3.1785315e-01, -4.5469920e-03,  6.4787251e-01],
        [ 7.1413435e-02,  1.0093837e+00, -1.4142343e-01,  6.8968758e-02,
         -8.9100498e-01,  6.3182700e-01,  2.0108935e-01, -2.0873295e-01,
         -1.1412679e+00, -2.8712434e-01,  5.5842286e-01]], dtype=float32),
 array([ 1.2091901 ,  0.15602335,  0.53412586,  0.2918139 ,  0.5585337 ,
        -0.06298493, -0.38151208,  0.14340456, -0.26255214,  0.62285376,
         0.4749198 ], dtype=float32)]

In [119]:
model.layers[1].get_weights()

[array([[-0.93161535,  0.3915667 , -0.6372322 , -0.27374598, -1.5625057 ,
          0.09459934, -0.3043398 ,  0.25855926,  0.432636  ,  0.33230022,
         -0.02248659],
        [ 0.26511928, -0.32362717,  0.10908853,  0.17717032,  0.15480343,
         -0.7349019 ,  0.01931904,  0.56569946,  0.73372304,  0.6509644 ,
         -0.36233455],
        [ 0.38850263, -0.30727506,  0.38177493,  0.13891087,  0.06319427,
          0.46286973, -0.00815521, -0.45916626, -0.0668764 , -1.5548651 ,
         -0.50599027],
        [ 0.34508464,  0.14167294, -0.7719561 , -0.05031357, -0.07030387,
         -0.5698186 ,  0.24659102, -0.28110492,  0.16603099, -0.7588306 ,
          0.23253554],
        [ 0.2932517 ,  0.05355064,  0.287857  ,  0.58741635,  0.09119312,
         -0.3814531 ,  0.9030138 ,  0.7217907 ,  0.24207175, -0.03276134,
          0.29645517],
        [ 0.5738595 ,  0.5756864 , -0.57250196,  0.7145535 ,  0.30851737,
          0.9324289 , -0.07318814, -1.521544  ,  0.0697742 ,  0.17410451,
         -0.32698882],
        [-0.474002  ,  0.17743915,  0.31092042, -0.7404686 , -0.5235671 ,
          0.21110088, -0.55790365, -0.5082433 ,  0.2705724 ,  0.10525616,
          0.9155766 ],
        [ 0.23867816, -0.3771763 ,  0.7838066 ,  0.1596856 ,  0.054768  ,
         -0.2451216 , -0.6065154 , -0.15491009,  0.75928026,  0.2315378 ,
          0.16230614],
        [-0.6754748 ,  0.50330156,  0.44676766,  0.01034102,  0.2778569 ,
         -0.5894041 ,  0.33485416, -0.31811193,  0.15168978, -0.49997348,
          0.40692288],
        [ 0.3477909 , -2.2647154 ,  0.09414451,  0.34479374,  0.4100828 ,
          0.09536657, -0.29259756,  0.42906427,  0.35396752,  0.17732212,
          0.7388017 ],
        [-0.17281768, -0.79602313, -0.08350305, -0.06098848,  0.3353956 ,
          0.15631075, -0.1799326 ,  0.23518908, -0.3474108 ,  0.24015735,
          0.74631476]], dtype=float32),
 array([ 0.23348537, -0.14165306,  0.01155528,  0.15039524,  0.60835475,
         0.2536718 ,  0.492222  , -0.5363542 ,  0.13371547,  0.17204927,
         0.1227772 ], dtype=float32)]

In [121]:
model.layers[2].get_weights()

[array([[ 1.3771585 ],
        [ 1.6621319 ],
        [ 1.120249  ],
        [ 0.5713571 ],
        [ 0.9088976 ],
        [ 0.59604484],
        [-1.4832458 ],
        [ 1.1021242 ],
        [-0.8812846 ],
        [-1.0910277 ],
        [-1.0544256 ]], dtype=float32),
 array([-0.20735435], dtype=float32)]

In [123]:
y_pred=model.predict(x_test)
y_pred

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

array([[0.02306982],
       [0.09426511],
       [0.09251503],
       ...,
       [0.00202616],
       [0.04570076],
       [0.40977967]], dtype=float32)

In [124]:
y_pred=y_pred.argmax(axis=-1)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [125]:
from sklearn.metrics import accuracy_score

In [126]:
accuracy_score(y_test,y_pred)

0.7925

In [141]:
y_pred_train=model.predict(x_train)
y_pred_train

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

array([[0.02053389],
       [0.06560426],
       [0.6803738 ],
       ...,
       [0.56624043],
       [0.03489532],
       [0.37088025]], dtype=float32)

In [142]:
y_pred_train=y_pred_train.argmax(axis=-1)
y_pred_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [143]:
accuracy_score(y_train,y_pred_train)

0.79725