In [51]:
import numpy as np
import pandas as pd

In [53]:
df=pd.read_csv('1.ushape.csv',header=None,names=['X','Y','Class'])
df

           X         Y  Class
0   0.031595  0.986988    0.0
1   2.115098 -0.046244    1.0
2   0.882490 -0.075756    0.0
3  -0.055144 -0.037332    1.0
4   0.829545 -0.539321    1.0
..       ...       ...    ...
95  1.699453  0.587720    1.0
96  0.218623 -0.652521    1.0
97  0.952914 -0.419766    1.0
98 -1.318500  0.423112    0.0
99 -1.296818  0.184147    0.0

[100 rows x 3 columns]

In [55]:
x=df.iloc[:,0:2]
y=df.iloc[:,-1]

In [57]:
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [59]:
model1=Sequential()

model1.add(Dense(10,activation='tanh',input_dim=2))
model1.add(Dense(10,activation='tanh'))

model1.add(Dense(10,activation='tanh'))
model1.add(Dense(10,activation='tanh'))
model1.add(Dense(1,activation='sigmoid'))
model1.summary()

C:\Users\cipl\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_20 (Dense)                     │ (None, 10)                  │              30 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_21 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_22 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_23 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_24 (Dense)                     │ (None, 1)                   │              11 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 371 (1.45 KB)

 Trainable params: 371 (1.45 KB)

 Non-trainable params: 0 (0.00 B)

In [60]:
model1.get_weights()

[array([[ 0.37389952,  0.1880117 ,  0.48772365,  0.4239766 ,  0.63989455,
          0.31309325,  0.24195981, -0.55844486, -0.20944673, -0.578714  ],
        [-0.179147  , -0.48513484, -0.642207  , -0.21359989, -0.266494  ,
          0.59645087,  0.19598502,  0.65771157,  0.09918875, -0.553628  ]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[ 1.6119939e-01,  1.9964111e-01, -4.0726519e-01, -2.5704715e-01,
         -3.1082594e-01,  3.6144131e-01,  9.7407997e-02, -4.3796295e-01,
         -1.1452711e-01, -1.9087034e-01],
        [ 4.7510004e-01,  7.3252678e-02,  4.6579003e-01,  4.7117758e-01,
          8.6545229e-02,  2.7303272e-01,  4.8809981e-01, -7.0889682e-02,
          2.9955775e-01,  4.6307981e-01],
        [-3.4293592e-01,  2.4357498e-02,  4.8926055e-02,  4.5233417e-01,
         -5.1844025e-01,  1.5969747e-01,  3.3809304e-02,  1.5142781e-01,
         -3.1924295e-01,  1.2146896e-01],
        [ 4.7085488e-01, -2.2791666e-01,  4.5666540e-01, -7.3511600e-02,
          4.4871670e-01,  2.3368168e-01,  9.2805862e-02,  6.6105485e-02,
          4.4281924e-01,  5.2439880e-01],
        [ 2.6610219e-01,  3.8258523e-01, -1.4816794e-01, -3.9043105e-01,
          5.6417584e-03, -5.3021789e-01,  4.2716771e-01, -3.3458018e-01,
         -1.7381567e-01, -3.6140424e-01],
        [-8.7422013e-02, -1.6975376e-01,  2.3809946e-01,  4.5316637e-02,
         -3.1008255e-01, -7.0164800e-03,  1.7889732e-01,  3.0127430e-01,
         -4.6770865e-01, -4.3915927e-01],
        [ 3.9027327e-01, -5.0548309e-01,  2.4711883e-01,  1.2560362e-01,
         -3.4280640e-01,  3.4933132e-01,  4.9392354e-01,  3.0803072e-01,
         -5.2827471e-01,  2.4830735e-01],
        [ 5.1210523e-01, -1.8476784e-02,  7.4685991e-02,  4.8655713e-01,
         -4.9024826e-01, -1.7542607e-01, -4.6889189e-01, -4.7946632e-01,
         -5.6913197e-02,  3.6665422e-01],
        [ 2.5504601e-01, -7.7578366e-02,  2.5640124e-01,  1.1946619e-02,
          3.8509917e-01, -2.8810680e-02,  2.1541971e-01, -6.1153620e-02,
          4.9716783e-01,  5.2982819e-01],
        [ 3.3601546e-01, -8.7504417e-02,  3.3760732e-01,  3.7888050e-02,
         -3.6409760e-01, -3.8129091e-04,  4.3642700e-01, -2.9433736e-01,
          3.1109548e-01,  4.2183912e-01]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[ 0.42966986,  0.4433148 ,  0.31805813,  0.35844815,  0.24247402,
         -0.14123192, -0.48564872,  0.2628132 ,  0.19183916,  0.09213555],
        [-0.211719  ,  0.20360559, -0.38754323,  0.02829188,  0.29280233,
         -0.39795953,  0.40638554, -0.42214805, -0.34159532, -0.3602907 ],
        [-0.06743851,  0.46682537, -0.28008443,  0.50865304, -0.07257894,
          0.12920403,  0.29926062, -0.04516345, -0.40515357,  0.02873349],
        [ 0.5450429 , -0.03995097, -0.25070766, -0.13232091, -0.20108527,
          0.39484042, -0.22860995,  0.49985373, -0.4425215 ,  0.43598652],
        [-0.44415253, -0.22446275, -0.28513566,  0.4823469 , -0.39627025,
          0.29110587,  0.17977071, -0.11460218, -0.07627064,  0.39607346],
        [ 0.47116518, -0.54145545, -0.18555677, -0.37250805,  0.02246648,
         -0.01645648,  0.43146664,  0.53578365, -0.37812656, -0.39941895],
        [-0.19610193, -0.05406913, -0.518733  ,  0.32735503,  0.47403824,
         -0.5120213 ,  0.5163102 , -0.43867466,  0.2476502 , -0.46135452],
        [ 0.03496605,  0.2558998 , -0.22529787,  0.2174319 , -0.46065536,
         -0.27227387,  0.01354074, -0.1518091 , -0.35927096,  0.29551697],
        [-0.1761131 ,  0.35271847, -0.48486596,  0.47376359, -0.22276172,
          0.47729492,  0.46945047,  0.38943136,  0.35203105,  0.5102246 ],
        [ 0.11140031, -0.25858897,  0.3022771 , -0.06920093,  0.05843729,
          0.24278033,  0.0930382 ,  0.35703063, -0.02376765, -0.00955611]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.33334482, -0.29973102, -0.05636615, -0.5053393 ,  0.46659315,
         -0.23369917, -0.3361966 ,  0.5384817 , -0.22350919, -0.3679486 ],
        [-0.0131585 , -0.04669994,  0.32401228,  0.36332607,  0.29207325,
          0.5258939 , -0.39568114,  0.28187752,  0.01301813,  0.27314687],
        [-0.3625683 ,  0.46628904, -0.27434525,  0.39433324,  0.39565176,
          0.09130281,  0.43033743,  0.37357968, -0.5203874 , -0.46034938],
        [-0.16583821,  0.05157006,  0.27246296,  0.2512927 , -0.37629157,
         -0.22873256, -0.30732465, -0.08721137,  0.05242413, -0.428308  ],
        [ 0.4329152 ,  0.27623433, -0.27399632,  0.17045355,  0.08885771,
         -0.19032425,  0.22993904,  0.2977376 ,  0.33170754,  0.4351253 ],
        [-0.20395991,  0.14118451, -0.13321438,  0.3233267 ,  0.28687704,
         -0.3661396 ,  0.34871954, -0.0986802 , -0.42914128,  0.06524581],
        [-0.4101829 ,  0.47674775,  0.34512562,  0.10791975, -0.33235538,
         -0.3867422 ,  0.49344742,  0.05195361,  0.39100093,  0.06538463],
        [ 0.29270488, -0.25948676,  0.25861627, -0.01700884,  0.2320044 ,
          0.29773003, -0.43427294, -0.42704624,  0.4583162 , -0.01891595],
        [ 0.22617269,  0.45621264, -0.4693483 , -0.30967274,  0.06493503,
          0.08232808,  0.5322231 ,  0.42964822, -0.09330484,  0.17236221],
        [ 0.28811556,  0.13604563,  0.4426074 ,  0.50620997,  0.0875957 ,
          0.05472702, -0.48592675,  0.34335327,  0.21778673,  0.16725993]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.58187205],
        [-0.5112709 ],
        [ 0.17646235],
        [ 0.17269206],
        [ 0.15231633],
        [ 0.68372494],
        [ 0.02900696],
        [ 0.00808102],
        [-0.11528999],
        [ 0.5552873 ]], dtype=float32),
 array([0.], dtype=float32)]

In [62]:
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [73]:
history=model1.fit(x,y,epochs=100,validation_split=0.2)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.8430 - loss: 0.3814 - val_accuracy: 0.9000 - val_loss: 0.2693
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8742 - loss: 0.3454 - val_accuracy: 0.9000 - val_loss: 0.2686
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8547 - loss: 0.3787 - val_accuracy: 0.9000 - val_loss: 0.2683
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8859 - loss: 0.3212 - val_accuracy: 0.9000 - val_loss: 0.2673
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8547 - loss: 0.3666 - val_accuracy: 0.9000 - val_loss: 0.2674
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8430 - loss: 0.3807 - val_accuracy: 0.9000 - val_loss: 0.2674
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8547 - loss: 0.3598 - val_accuracy: 0.9000 - val_loss: 0.2668
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8859 - loss: 0.3104 - val_accuracy: 0.9000 - val_loss: 0.2665
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8586 - loss: 0.3383 - val_accuracy: 0.9000 - val_loss: 0.2674
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8469 - loss: 0.3696 - val_accuracy: 0.9000 - val_loss: 0.2678
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8313 - loss: 0.3941 - val_accuracy: 0.9000 - val_loss: 0.2678
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8820 - loss: 0.3201 - val_accuracy: 0.9000 - val_loss: 0.2669
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8430 - loss: 0.3918 - val_accuracy: 0.9000 - val_loss: 0.2674
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8352 - loss: 0.3851 - val_accuracy: 0.9000 - val_loss: 0.2675
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.8469 - loss: 0.3598 - val_accuracy: 0.9000 - val_loss: 0.2675
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8703 - loss: 0.3308 - val_accuracy: 0.9000 - val_loss: 0.2675
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8475 - loss: 0.3695 - val_accuracy: 0.9000 - val_loss: 0.2679
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8352 - loss: 0.3811 - val_accuracy: 0.9000 - val_loss: 0.2681
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.8508 - loss: 0.3783 - val_accuracy: 0.9000 - val_loss: 0.2686
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.8352 - loss: 0.3795 - val_accuracy: 0.9000 - val_loss: 0.2689
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8586 - loss: 0.3559 - val_accuracy: 0.9000 - val_loss: 0.2679
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8703 - loss: 0.3376 - val_accuracy: 0.9000 - val_loss: 0.2664
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8547 - loss: 0.3380 - val_accuracy: 0.9000 - val_loss: 0.2653
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.8508 - loss: 0.3798 - val_accuracy: 0.9000 - val_loss: 0.2660
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.8703 - loss: 0.3552 - val_accuracy: 0.9000 - val_loss: 0.2673
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.8195 - loss: 0.4162 - val_accuracy: 0.9000 - val_loss: 0.2685
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8586 - loss: 0.3466 - val_accuracy: 0.9000 - val_loss: 0.2679
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.8508 - loss: 0.3516 - val_accuracy: 0.9000 - val_loss: 0.2668
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.8352 - loss: 0.4004 - val_accuracy: 0.9000 - val_loss: 0.2664
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8586 - loss: 0.3437 - val_accuracy: 0.9000 - val_loss: 0.2652
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8664 - loss: 0.3433 - val_accuracy: 0.9000 - val_loss: 0.2652
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.8508 - loss: 0.3556 - val_accuracy: 0.9000 - val_loss: 0.2656
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8547 - loss: 0.3606 - val_accuracy: 0.9000 - val_loss: 0.2654
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8625 - loss: 0.3324 - val_accuracy: 0.9000 - val_loss: 0.2660
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8508 - loss: 0.3719 - val_accuracy: 0.9000 - val_loss: 0.2663
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8664 - loss: 0.3435 - val_accuracy: 0.9000 - val_loss: 0.2656
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.8430 - loss: 0.3824 - val_accuracy: 0.9000 - val_loss: 0.2650
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8586 - loss: 0.3447 - val_accuracy: 0.9000 - val_loss: 0.2634
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8508 - loss: 0.3745 - val_accuracy: 0.9000 - val_loss: 0.2621
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8430 - loss: 0.3701 - val_accuracy: 0.9000 - val_loss: 0.2601
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.8664 - loss: 0.3217 - val_accuracy: 0.9000 - val_loss: 0.2593
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.8469 - loss: 0.3627 - val_accuracy: 0.9000 - val_loss: 0.2586
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.8234 - loss: 0.3935 - val_accuracy: 0.9000 - val_loss: 0.2582
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.8273 - loss: 0.4083 - val_accuracy: 0.9000 - val_loss: 0.2577
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8781 - loss: 0.3208 - val_accuracy: 0.9000 - val_loss: 0.2561
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8664 - loss: 0.3315 - val_accuracy: 0.9000 - val_loss: 0.2559
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8547 - loss: 0.3542 - val_accuracy: 0.9000 - val_loss: 0.2572
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8547 - loss: 0.3719 - val_accuracy: 0.9000 - val_loss: 0.2593
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8430 - loss: 0.3644 - val_accuracy: 0.9000 - val_loss: 0.2590
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8586 - loss: 0.3527 - val_accuracy: 0.9000 - val_loss: 0.2591
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8430 - loss: 0.3606 - val_accuracy: 0.9000 - val_loss: 0.2597
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8313 - loss: 0.3927 - val_accuracy: 0.9000 - val_loss: 0.2592
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8469 - loss: 0.3688 - val_accuracy: 0.9000 - val_loss: 0.2580
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8469 - loss: 0.3483 - val_accuracy: 0.9000 - val_loss: 0.2586
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8391 - loss: 0.3759 - val_accuracy: 0.9000 - val_loss: 0.2595
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8352 - loss: 0.3704 - val_accuracy: 0.9000 - val_loss: 0.2590
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8469 - loss: 0.3658 - val_accuracy: 0.9000 - val_loss: 0.2568
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8625 - loss: 0.3478 - val_accuracy: 0.9000 - val_loss: 0.2557
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8313 - loss: 0.3828 - val_accuracy: 0.9000 - val_loss: 0.2548
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8742 - loss: 0.3109 - val_accuracy: 0.9000 - val_loss: 0.2544
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8234 - loss: 0.3902 - val_accuracy: 0.9000 - val_loss: 0.2547
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8586 - loss: 0.3384 - val_accuracy: 0.9000 - val_loss: 0.2534
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8273 - loss: 0.4056 - val_accuracy: 0.9000 - val_loss: 0.2514
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8430 - loss: 0.3623 - val_accuracy: 0.9000 - val_loss: 0.2485
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8430 - loss: 0.3599 - val_accuracy: 0.9000 - val_loss: 0.2460
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8547 - loss: 0.3440 - val_accuracy: 0.9000 - val_loss: 0.2460
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8586 - loss: 0.3393 - val_accuracy: 0.9000 - val_loss: 0.2475
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8391 - loss: 0.3503 - val_accuracy: 0.9000 - val_loss: 0.2498
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.8508 - loss: 0.3397 - val_accuracy: 0.9000 - val_loss: 0.2515
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.8664 - loss: 0.3338 - val_accuracy: 0.9000 - val_loss: 0.2526
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8352 - loss: 0.3877 - val_accuracy: 0.9000 - val_loss: 0.2539
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8703 - loss: 0.3304 - val_accuracy: 0.9000 - val_loss: 0.2520
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8625 - loss: 0.3251 - val_accuracy: 0.9000 - val_loss: 0.2487
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8586 - loss: 0.3227 - val_accuracy: 0.9000 - val_loss: 0.2452
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.8391 - loss: 0.3537 - val_accuracy: 0.9000 - val_loss: 0.2432
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8156 - loss: 0.3977 - val_accuracy: 0.9500 - val_loss: 0.2429
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8781 - loss: 0.3171 - val_accuracy: 0.9500 - val_loss: 0.2410
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8391 - loss: 0.3516 - val_accuracy: 0.9500 - val_loss: 0.2401
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.8391 - loss: 0.3547 - val_accuracy: 0.9500 - val_loss: 0.2396
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8537 - loss: 0.3396 - val_accuracy: 0.9500 - val_loss: 0.2391
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8469 - loss: 0.3243 - val_accuracy: 0.9500 - val_loss: 0.2386
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8475 - loss: 0.3351 - val_accuracy: 0.9500 - val_loss: 0.2406
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8586 - loss: 0.3247 - val_accuracy: 0.9500 - val_loss: 0.2422
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8820 - loss: 0.2827 - val_accuracy: 0.9500 - val_loss: 0.2449
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8664 - loss: 0.3206 - val_accuracy: 0.9500 - val_loss: 0.2476
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8664 - loss: 0.3062 - val_accuracy: 0.9500 - val_loss: 0.2491
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8469 - loss: 0.3368 - val_accuracy: 0.9500 - val_loss: 0.2467
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.8313 - loss: 0.3600 - val_accuracy: 0.9500 - val_loss: 0.2440
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8508 - loss: 0.3460 - val_accuracy: 0.9500 - val_loss: 0.2405
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8859 - loss: 0.2862 - val_accuracy: 0.9500 - val_loss: 0.2354
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.8352 - loss: 0.3554 - val_accuracy: 0.9500 - val_loss: 0.2323
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.8508 - loss: 0.3310 - val_accuracy: 0.9500 - val_loss: 0.2296
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8430 - loss: 0.3324 - val_accuracy: 0.9500 - val_loss: 0.2269
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8547 - loss: 0.3358 - val_accuracy: 0.9500 - val_loss: 0.2269
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8234 - loss: 0.3502 - val_accuracy: 0.9500 - val_loss: 0.2257
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.8703 - loss: 0.3061 - val_accuracy: 0.9500 - val_loss: 0.2247
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8352 - loss: 0.3230 - val_accuracy: 0.9500 - val_loss: 0.2224
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8961 - loss: 0.2693 - val_accuracy: 0.9500 - val_loss: 0.2229
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.8648 - loss: 0.3056 - val_accuracy: 0.9500 - val_loss: 0.2265
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8453 - loss: 0.3312 - val_accuracy: 0.9500 - val_loss: 0.2304

In [66]:
# model1.get_weights()

In [75]:
from mlxtend.plotting import plot_decision_regions
plot_decision_regions(x,y.astype('int'), clf=model1, legend=2)

ValueError: X must be a NumPy array. Found <class 'pandas.core.frame.DataFrame'>

NameError: name 'Y' is not defined

In [45]:
X

           X         Y
0   0.031595  0.986988
1   2.115098 -0.046244
2   0.882490 -0.075756
3  -0.055144 -0.037332
4   0.829545 -0.539321
..       ...       ...
95  1.699453  0.587720
96  0.218623 -0.652521
97  0.952914 -0.419766
98 -1.318500  0.423112
99 -1.296818  0.184147

[100 rows x 2 columns]